Encoding.default_external = "UTF-8"
source 'https://supermarket.chef.io'

metadata

cookbook 'conda', github: "kouzant/conda-chef", branch: "HOPSWORKS-2705"
cookbook 'kagent', github: "kouzant/kagent-chef", branch: "HOPSWORKS-2705"
cookbook 'hops', github: "kouzant/hops-hadoop-chef", branch: "HOPSWORKS-2705"
cookbook 'ndb', github: "kouzant/ndb-chef", branch: "HOPSWORKS-2705"
cookbook 'hadoop_spark', github: "kouzant/spark-chef", branch: "HOPSWORKS-2705"
cookbook 'flink', github: "kouzant/flink-chef", branch: "HOPSWORKS-2705"
cookbook 'livy', github: "kouzant/livy-chef", branch: "HOPSWORKS-2705"
cookbook 'epipe', github: "logicalclocks/epipe-chef", branch: "master"
cookbook 'tensorflow', github: "logicalclocks/tensorflow-chef", branch: "master"
cookbook 'dela', github: "logicalclocks/dela-chef", branch: "master"
cookbook 'kzookeeper', github: "kouzant/kzookeeper", branch: "HOPSWORKS-2705"
cookbook 'kkafka', github: "kouzant/kafka-cookbook", branch: "HOPSWORKS-2705"
cookbook 'elastic', github: "kouzant/elasticsearch-chef", branch: "HOPSWORKS-2705"
cookbook 'hopslog', github: "kouzant/hopslog-chef", branch: "HOPSWORKS-2705"
cookbook 'hopsmonitor', github: "kouzant/hopsmonitor-chef", branch: "HOPSWORKS-2705"
cookbook 'hops_airflow', github: "kouzant/airflow-chef", branch: "HOPSWORKS-2705"
cookbook 'hive2', github: "kouzant/hive-chef", branch: "HOPSWORKS-2705"
cookbook 'consul', github: "kouzant/consul-chef", branch: "HOPSWORKS-2705"
cookbook 'kube-hops', github: "kouzant/kube-hops-chef", branch: "HOPSWORKS-2705"
cookbook 'cloud', github: "logicalclocks/cloud-chef", branch: "master"
cookbook 'onlinefs', github: "kouzant/onlinefs-chef", branch: "HOPSWORKS-2705"

cookbook 'ulimit', github: "logicalclocks/chef-ulimit", branch: "master"
cookbook 'glassfish', github: "logicalclocks/chef-glassfish", branch: "master"
cookbook 'java', github: "logicalclocks/java", branch: "v7.0.0-1"
