Encoding.default_external = "UTF-8"
source 'https://supermarket.chef.io'

metadata

cookbook 'conda', github: "gibchikafa/conda-chef", branch: "remove_gnu"
cookbook 'kagent', github: "gibchikafa/kagent-chef", branch: "ubuntu_upgrade"
cookbook 'hops', github: "kouzant/hops-hadoop-chef", branch: "centos8_ubu22"
cookbook 'ndb', github: "gibchikafa/ndb-chef", branch: "ubuntu_upgrade"
cookbook 'hadoop_spark', github: "logicalclocks/spark-chef", branch: "master"
cookbook 'flink', github: "logicalclocks/flink-chef", branch: "master"
cookbook 'livy', github: "logicalclocks/livy-chef", branch: "master"
cookbook 'epipe', github: "gibchikafa/epipe-chef", branch: "CLOUD-390"
cookbook 'tensorflow', github: "logicalclocks/tensorflow-chef", branch: "master"
cookbook 'kzookeeper', github: "logicalclocks/kzookeeper", branch: "master"
cookbook 'kkafka', github: "logicalclocks/kafka-cookbook", branch: "master"
cookbook 'elastic', github: "logicalclocks/elasticsearch-chef", branch: "master"
cookbook 'hopslog', github: "logicalclocks/hopslog-chef", branch: "master"
cookbook 'hopsmonitor', github: "gibchikafa/hopsmonitor-chef", branch: "upgrade"
cookbook 'hops_airflow', github: "logicalclocks/airflow-chef", branch: "master"
cookbook 'hive2', github: "logicalclocks/hive-chef", branch: "master"
cookbook 'consul', github: "logicalclocks/consul-chef", branch: "master"
cookbook 'kube-hops', github: "gibchikafa/kube-hops-chef", branch: "upgrade"
cookbook 'cloud', github: "logicalclocks/cloud-chef", branch: "master"
cookbook 'onlinefs', github: "gibchikafa/onlinefs-chef", branch: "ubuntu22.04_test"
cookbook 'flyingduck', github: "logicalclocks/flyingduck-chef", branch: "master"

cookbook 'ulimit', github: "logicalclocks/chef-ulimit", branch: "master"
cookbook 'glassfish', github: "logicalclocks/chef-glassfish", branch: "master"
cookbook 'java', github: "logicalclocks/java", branch: "v7.0.0-1"
